# Generated by Django 4.2.2 on 2023-06-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(limit_choices_to={'usertype': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reader_books',
            name='reader',
            field=models.ForeignKey(limit_choices_to={'usertype': 'reader'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reader_books',
            unique_together={('reader', 'book')},
        ),
    ]
