# Generated by Django 4.2.2 on 2023-06-28 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_author_alter_reader_books_reader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_books', to='book.book'),
        ),
        migrations.AlterField(
            model_name='reader_books',
            name='reader',
            field=models.ForeignKey(limit_choices_to={'usertype': 'reader'}, on_delete=django.db.models.deletion.CASCADE, related_name='reader_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
