# Generated by Django 4.2.2 on 2023-06-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_reader_books_book_alter_reader_books_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_readers', to='book.book'),
        ),
    ]
