# Generated by Django 4.2.2 on 2023-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_reader_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='http://127.0.0.1:8000/media/book_images/defaultBC.jpg', upload_to='book_images/'),
        ),
    ]
