# Generated by Django 4.2.2 on 2023-06-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_reader_books_book'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'page_number')},
        ),
    ]
