# Generated by Django 4.2.2 on 2023-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_page_number_alter_page_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
