# Generated by Django 4.2.2 on 2023-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='http://127.0.0.1:8000/media/book_images/defaultpp.jpeg', upload_to='profile_images/'),
        ),
    ]
