# Generated by Django 4.2.2 on 2023-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_images/defaultpp.jpeg', upload_to='profile_images/'),
        ),
    ]
