# Generated by Django 4.2.2 on 2023-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='A strong author bio establishes your authority, introduces readers to your background, and helps convince them to buy your book. ➡️ An author bio is usually no longer than 100 words, so keep it short and simple. Include your location, relevant experience, and key themes in your work'),
        ),
    ]
