# Generated by Django 4.2.2 on 2023-06-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
