# Generated by Django 4.2.2 on 2023-06-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_reader_books_delete_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Books.user')),
            ],
            bases=('Books.user',),
        ),
    ]
