# Generated by Django 4.2.2 on 2023-06-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader_books',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.reader'),
        ),
    ]
